apiVersion: v1
kind: Service
metadata:
  name: inventory-lb-qa
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    role: inventory-qa
  type: LoadBalancer
  loadBalancerIP: "34.135.4.147"